# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sean Hendicott
email: mark@berthelemy.net
description: "Heating and hot water specialist in Brittany, France"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

baseurl: "/seanhendicott"

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed

sass:
    sass_dir: _sass


collections:
    sections:
        output: false
    testimonials:
        output: false

collections_dir: _collections

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/


t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "#about"
    products:
      name: "Products"
      url: "#products"
    services:
      name: "Services"
      url: "#services"
    testimonials:
      name: "Testimonials"
      url: "#testimonials"
    contact:
      name: "Contact"
      title: "Contact Sean &amp; Karen"
      url: "#contact"
    description:
      name: "Heating and hot water specialist in Brittany, France"
    find-out:
      name: "Find out more"
    get-in-touch:
      name: "Get in touch to discuss your needs"
    email:
      name: "Your email"
    phone:
      name: "Your phone number"
    message:
      name: "Your message"
    send:
      name: "Send"
    landline:
      name: "Landline"
    s-mobile:
      name: "Sean's mobile"
    k-mobile:
      name: "Karen's mobile"
    facebook:
      name: "Find us on Facebook"
    base:
      name: "We are based near to Carhaix Plouguer in Department 29. So are ideally situated to service departments 22, 29 &amp; 56."
  fr:
    home:
      name: "Accueil"
      url: "/accueil/"
    about:
      name: "À propos"
      url: "#a-propos"
    products:
      name: "Produits"
      url: "#products"
    services:
      name: "Services"
      url: "#services"
    testimonials:
      name: "Témoinages"
      url: "#temoinages"
    contact:
      name: "Contact"
      title: "Contact Sean &amp; Karen"
      url: "#contact"
    description:
      name: "Spécialiste du chauffage et de l'eau chaude en Bretagne, France"
    find-out:
      name: "En savoir plus"
    get-in-touch:
      name: "Contactez-nous pour discuter de vos besoins"
    email:
      name: "Votre mail"
    phone:
      name: "Votre numéro telephone"
    message:
      name: "Votre message"
    send:
      name: "Envoyer"
    landline:
      name: "Ligne fixe"
    s-mobile:
      name: "Mobile de Sean"
    k-mobile:
      name: "Mobile de Karen"
    facebook:
      name: "Retrouvez-nous sur Facebook"
    base:
      name: "Nous sommes basés près de Carhaix Plouguer dans le département 29. Nous sommes donc idéalement situés pour desservir les départements 22, 29 & amp; 56."
